### ISSUE TITLE
Can't change a source

### ISSUE THREAD

**Issue by oandry72** [wizmo2/zidoo-player#4]
## Ziddo Z10
Firmware: v2.3.80

## Home Assistant Supervised on RaspberryPi 4 64bit

version | core-2021.12.10
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.92-v8+
arch | aarch64

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.12

The first time when I installed the integration it worked well, but after the last upgrade it stopped changing sources.
All others like play,pause,volume,media_prowser work.

When I try to change the source, I get the following error:

Filed to call service media_player/select_source. get_app_list() takes 1 positional argument but 2 were given

2022-02-02 12:06:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [547283208128] get_app_list() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 728, in async_select_source
    await self.hass.async_add_executor_job(self.select_source, source)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/zidoo/media_player.py", line 349, in select_source
    self._player.start_app(source)
  File "/config/custom_components/zidoo/zidoorc.py", line 634, in start_app
    self._app_list = self.get_app_list(log_errors)
TypeError: get_app_list() takes 1 positional argument but 2 were given

**Comment by wizmo2** [comment]
fixed in 1.2.8.

Thanks.

**Comment by oandry72** [comment]
Now it works.

Thank you very much.
